#!/usr/bin/env bash
# Install nginx on your web-01 server

# Updates the package list
sudo apt-get update

# This installs Nginx
sudo apt-get -y install nginx

# Configures Nginx to listen on port 80
sudo sed -i 's/80 default_server/80/g' /etc/nginx/sites-available/default

# Creates a page with "Hello World!" message
echo "Hello World!" | sudo tee /var/www/html/index.html

# This restarts Nginx
sudo service nginx start
