#!/usr/bin/env bash
# Display "Best School" 10 times using a while loop.
# On the 9th iteration, display "Best School" and then "Hi" on a new line.

counter=0

while [ $counter -lt 10 ]; do
    if [ $counter -eq 8 ]; then
        echo -n "Best School"; echo " Hi"
    else
        echo "Best School"
    fi
    ((counter++))
done
